export * from './videos.interface'
export * from './video.interface'
export * from './spokLaung.interface'
export * from './prodCount.interface'
export * from './genre.interface'
export * from './genres.interface'
export * from './movie.interface'
export * from './movies.interface'
export * from './creditsDetails.interface'
export * from './credits.interface'
export * from './images.interface'

